server:
  port:  8082
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s

iam-client:
  organization-id: it-testing-001
  project-id: spring-method-security
  base-url: http://127.0.0.1:8080
  polling-interval: 30
  time-unit: SECONDS

logging:
  level:
    root: INFO
