version: '3'
services:
  iam-service:
    image: iam-service:1.0.0-SNAPSHOT
    build:
      context: iam-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  spring-method-security:
    image: spring-method-security:1.0.0-SNAPSHOT
    build:
      context: iam-examples/spring-method-security
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - iam-service
  spring-resource-server:
    image: spring-resource-server:1.0.0-SNAPSHOT
    build:
      context: iam-examples/spring-resource-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - iam-service
