version: '3'
services:
  iam-service:
    image: iam-service:2.2.0-SNAPSHOT
    build:
      context: iam-service
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "8080:8080"
  spring-method-security:
    image: spring-method-security:2.2.0-SNAPSHOT
    build:
      context: iam-examples/spring-method-security
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "8082:8082"
    depends_on:
      - iam-service
  spring-resource-server:
    image: spring-resource-server:2.2.0-SNAPSHOT
    build:
      context: iam-examples/spring-resource-server
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "8081:8081"
    depends_on:
      - iam-service
  spring-webflux-secured:
    image: spring-webflux-secured:2.2.0-SNAPSHOT
    build:
      context: iam-examples/spring-webflux-secured
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "8083:8083"
    depends_on:
      - iam-service