server:
  port: 8081
  shutdown: graceful

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: iam-admins
          jwk-set-uri: http://127.0.0.1:8080/services/authentication/iam-admins/iam-admins/.well-known/jwks.json
          jws-algorithm: RS256
  lifecycle:
    timeout-per-shutdown-phase: 20s

logging:
  level:
    root: TRACE
