version: '3.7'

services:
  mongodb_container:
    image: mongo:4.4.4-bionic
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  redis_container:
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379

volumes:
  mongodb_data_container:
    driver: local
