server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/services/authentication/iam-admins/iam-admins
          jws-algorithm: RS256
logging:
  level:
    root: TRACE