server:
  port: 8080
  shutdown: graceful
#  servlet:
#    context-path: /auth
spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s

iam-service:
  authorization-code-cache:
    duration: 10
    timeunit: MINUTES
  cache-cleanup-interval:
    duration: 1
    timeunit: MINUTES
  data-model:
    default-admin-password: secret
    default-admin-client-secret: top-secret
    persistence: in-memory #options: in-memory | file-system
    #path: /path/to/model-storage.json #only for file-system persistence

logging:
  level:
    root: INFO
