server:
  port: 8080
iam-service:
  authorization-code-cache:
    duration: 10
    timeunit: MINUTES
  cache-cleanup-interval:
    duration: 1
    timeunit: MINUTES
  data-storage:
    password: secret
    persistence: in-memory #options: in-memory | file-system
    #path: /path/to/model-storage.json #only for file-system persistence

