apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-service
  namespace: iam-service
spec:
  selector:
    matchLabels:
      app: iam-service
  replicas: 2
  template:
    metadata:
      labels:
        app: iam-service
    spec:
      containers:
        - name: iam-service
          image: jurajveverka/iam-service:2.5.4-RELEASE-arm64v8
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
            requests:
              memory: 256Mi
              cpu: 500m