---
apiVersion: v1
kind: Namespace
metadata:
  name: iam-service
---
apiVersion: v1
kind: Secret
metadata:
  name: iam-service
  namespace: iam-service
type: Opaque
data:
  IAM_ADMIN_PASSWORD: c2VjcmV0
  IAM_ADMIN_CLIENT_SECRET: dG9wLXNlY3JldA==
  IAM_ADMIN_EMAIL: YWRtaW5AZW1haWwuY29t
  IAM_MONGO_PERSISTENCE_PASSWORD: c2VjcmV0
---
apiVersion: v1
kind: Service
metadata:
  name: iam-service
  namespace: iam-service
spec:
  selector:
    app: iam-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30081
  type: LoadBalancer
#  externalIPs:
#    - 192.168.44.210
